require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - Gemfile
    - vendor/**/*
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0.7
  SuggestExtensions: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/OpenStructUse:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ApplicationController:
  Enabled: false
